{{- if or .Values.ingress.external.enabled .Values.ingress.internal.enabled }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ required "A value for 'name' is required!" .Values.name }}-healthcheck
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ required "A value for 'name' is required!" .Values.name }}-service
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.service.ports.port | default 80 }}
        requestPath: {{ .Values.healthCheck.requestPath | default "/health/ready" }}
{{- end }}
